[package]
name = "taml-rs"
version = "0.2.0"
edition = "2024"
authors = ["Tomer Steinberg"]
description = "A lightweight, n-dimensional automatic differentiation library for learning and experimentation."
license = "MIT"
repository = "https://github.com/TomerSteinberg/taml"
readme = "README.md"
categories = ["science", "mathematics"]
keywords = ["machine-learning", "autodiff", "tensor"]

[lib]
name = "taml"

[dependencies]
ndarray = "0.17.2"
rand = "0.10.2"
